### ISSUE TITLE
How should I attribute this excellent site?

### ISSUE THREAD

**Issue by ioistired** [excellentorg/excellentrepo#2]
Inspired by the excellence of this excellent website, I went ahead and made [an excellent easter egg](https://posters.win/saelee) on my excellent website.

Per the terms of the excellent license "GPLv3", I must notify my excellent visitors that the excellent code is GPLv3 licensed and where to find the excellent source code.

Since this is a quite terrible (read: not excellent) burden on yours truly, the most excellent web developer, I request that I get an excellent exception to the License, to permit me to include just an attribution in the source code of the excellent easter egg, and no more.

May I excellently do that, your excellent-ness?

**Comment by Skaty** [comment]
As long as the excellent repository is linked from the excellent derivative work of this excellent work, then Chef Excellence would be pleased by it.

Placing the excellent reference/citation in the excellent source code would suffice, as it is still part of the excellent work.

Thank you for your interest in the work that celebrates excellence.
